{% set name = "boinor" %}
{% set version = "0.18.6" %}
{% set python_min = "3.9" %}
{% set python_max = "3.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/boinor-{{ version }}.tar.gz
  sha256: 6de98cb0d688e1927bb48b91daa9c54ef14d55d46d51cd9025b3fbb1b8a56fc6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4, <4
  run:
    - astropy-base <7,>=6.0
    - astroquery >=0.3.9
    - jplephem
    - matplotlib-base !=3.0.1,>=2.0
    - numba >=0.53.0
    - numpy <=1.30
    - pandas
    - plotly <6,>=4.0
    - pyerfa
    - python >={{ python_min }}, <={{ python_max }}
    - scipy >=1.4.0
    - cached-property
    - pyerfa
    - czml3

test:
  imports:
    - boinor
    - boinor.constants
    - boinor.twobody
    - boinor.threebody
    - boinor.iod
    - boinor.frames
    - boinor.plotting
    - boinor.ephem
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/boinor/
  summary: Utilities and Python wrappers for Orbital Mechanics.
  dev_url: https://github.com/boinor/boinor
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - boinor
